2022-02-13 13:09:13,908 DEBUG    decorator.py Была вызвана функция arg_parser(), вызов произошёл из функции main()
2022-02-13 13:09:13,910 INFO     server.py Запущен сервер, порт для подключений: 7777, адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-02-13 13:09:13,947 INFO     server.py Установлено соедение с ПК ('127.0.0.1', 48004)
2022-02-13 13:09:14,327 INFO     server.py Установлено соедение с ПК ('127.0.0.1', 48006)
2022-02-13 13:09:14,328 DEBUG    decorator.py Была вызвана функция get_message(), вызов произошёл из функции main_loop()
2022-02-13 13:09:14,328 DEBUG    server.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1644746953.9473758, 'user': {'account_name': 'test1'}}
2022-02-13 13:09:14,329 DEBUG    decorator.py Была вызвана функция send_message(), вызов произошёл из функции process_client_message()
2022-02-13 13:09:14,351 INFO     server.py Установлено соедение с ПК ('127.0.0.1', 48008)
2022-02-13 13:09:14,352 DEBUG    decorator.py Была вызвана функция get_message(), вызов произошёл из функции main_loop()
2022-02-13 13:09:14,352 DEBUG    server.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1644746954.327132, 'user': {'account_name': 'test3'}}
2022-02-13 13:09:14,353 DEBUG    decorator.py Была вызвана функция send_message(), вызов произошёл из функции process_client_message()
2022-02-13 13:09:14,857 DEBUG    decorator.py Была вызвана функция get_message(), вызов произошёл из функции main_loop()
2022-02-13 13:09:14,858 DEBUG    server.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1644746954.351374, 'user': {'account_name': 'test2'}}
2022-02-13 13:09:14,861 DEBUG    decorator.py Была вызвана функция send_message(), вызов произошёл из функции process_client_message()
2022-02-13 13:09:19,868 INFO     server.py Клиент ('127.0.0.1', 48008) отключился от сервера.
2022-02-13 13:09:21,371 INFO     server.py Клиент ('127.0.0.1', 48006) отключился от сервера.
2022-02-13 13:09:21,872 INFO     server.py Клиент ('127.0.0.1', 48004) отключился от сервера.
